server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    username: user
    password: 1234
    url: jdbc:mysql://localhost:3308/apsas_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
