server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: never  

spring:
  data:
    redis:
      host: localhost
      port: 6379
  ai:
    model:
      chat: openai
    openai:
      api-key: ${GEMINI_API_KEY}        # dùng Gemini API key
      chat:
        base-url: https://generativelanguage.googleapis.com
        api-key: ${GEMINI_API_KEY}     # hoặc spring.ai.openai.chat.api-key (tùy version)
        options:
          model: gemini-2.5-flash
        completions-path: /v1beta/openai/chat/completions
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 1000
      thread-name-prefix: app-async-
  datasource:
    username: user
    password: 1234
    url: jdbc:mysql://localhost:3308/apsas_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.use.type.headers: true
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.project.apsas.*"
      group-id: group_one
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.use.type.headers: true
    listener:
      ack-mode: manual_immediate
      concurrency: 3
#logging:
#  level:
#    org.springframework.kafka.config: DEBUG
#    org.springframework.kafka.listener: DEBUG

message-queue:
  topic:
    mail:
      name: topic-mail
      dlt: topic-mail.DLT
      drop: topic-mail.DLT.DROP
    feedback:
      name: topic-ai

cloudinary:
  cloud-name: ddcyjcpx0
  api-key: 197971381659871
  api-secret: 6g3wTrSYbG9B5T5kPps5olGXOuM
  option:
    folder-name: uploads/general
    resource-type: auto
jwt:
  signerKey: "JvLr4on9xnJj75gmh3fnVFdx9xELXish"
brevo:
  base-url: https://api.brevo.com/v3
  api-key: ${API_KEY_BREVO:dummy-key-for-dev}
  template-id: 3
  sender:
    mail: nguyentrongduc447@gmail.com
    name: CodeVerse
mvc:
  thow-exception-if-no-handler-found: true
web:
  resources:
    add-mappings: false 

app:
  verify:
    ttl-minutes: 10
  kafka:
    topic:
      verify-email: verify-email


